[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true 
evm_version='shanghai'
optimizer=true
optimizer_runs=1_000

 
remappings = [
    "foundry-huff/=lib/foundry-huff/src/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@chimera/=lib/chimera/src/"
]

[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 500
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_run_limit = 5000


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
